name: thirty_seven_degrees
description: 37° mobile app rebuilt on Flutter.
publish_to: 'none'
version: 0.6.0-dev.2+2026043001

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
